-- List Options for LBF ---
INSERT INTO list_options (list_id, option_id, title, seq, is_default, option_value, mapping, notes) VALUES
('lists', 'Capillary_Filling_Time', 'Capillary Filling Time', 63, 1, 0, '', ''),
('Capillary_Filling_Time', '2', 'Less than 2 seconds', 10, 0, 0, '', ''),
('Capillary_Filling_Time', '3', 'Less than 3 seconds', 20, 0, 0, '', ''),
('Capillary_Filling_Time', '4', 'Less than 4 seconds', 30, 0, 0, '', ''),
('lists', 'Deep_Tendon_Reflexes', 'Deep Tendon Reflexes', 66, 1, 0, '', ''),
('Deep_Tendon_Reflexes', '0', '0', 5, 0, 0, '', ''),
('Deep_Tendon_Reflexes', '1', '1', 4, 0, 0, '', ''),
('Deep_Tendon_Reflexes', '2', '2', 3, 0, 0, '', ''),
('Deep_Tendon_Reflexes', '3', '3', 2, 0, 0, '', ''),
('Deep_Tendon_Reflexes', '4', '4', 1, 0, 0, '', ''),
('Deep_Tendon_Reflexes', '5', '5', 0, 1, 0, '', ''),
('lists', 'Distress_Level', 'Distress Level', 61, 1, 0, '', ''),
('Distress_Level', 'apprehensive', 'Apprenhensive', 30, 0, 0, '', ''),
('Distress_Level', 'distresses', 'Distressed', 20, 0, 0, '', ''),
('Distress_Level', 'none', 'No Acute Distress', 10, 1, 0, '', ''),
('lbfnames', 'LBFhpi', 'History of Present Illness', 5, 0, 0, '', 'menu{Clinical}'),
('lbfnames', 'LBFimpression', 'Diagnosis / Impressions', 30, 0, 0, '', 'menu{Clinical}'),
('lbfnames', 'LBFplan', 'Treatment Plan', 40, 0, 0, '', 'menu{Clinical}'),
('lbfnames', 'LBFpodphyexam', 'Podiatry Physical Exam', 10, 0, 0, '', 'menu{Clinical}'),
('lbfnames', 'LBFsimpleros', 'Review of Systems', 0, 0, 0, '', 'menu{Clinical}'),
('lbfnames', 'LBFxray', 'Xray, Radiograph Evaluation', 20, 0, 0, '', 'menu{Clinical}'),
('lists', 'Pedal_Pulses', 'Pedal Pulses', 62, 1, 0, '', ''),
('Pedal_Pulses', '16', '1/4', 2, 0, 0, '', ''),
('Pedal_Pulses', '24', '2/4', 3, 0, 0, '', ''),
('Pedal_Pulses', '34', '3/4', 4, 0, 0, '', ''),
('lists', 'Positive_Negative', 'Positive_Negative', 65, 1, 0, '', ''),
('Positive_Negative', 'neg', 'Negative', 20, 1, 0, '', ''),
('Positive_Negative', 'pos', 'Positive', 10, 0, 0, '', ''),
('lists', 'Temperature_Gradients', 'Temperature Gradients', 64, 1, 0, '', ''),
('Temperature_Gradients', 'c2cold', 'Cool to Cold', 30, 0, 0, '', ''),
('Temperature_Gradients', 'c2cool', 'Cool to Cool', 20, 0, 0, '', ''),
('Temperature_Gradients', 'w2cool', 'Warm to Cool', 10, 0, 0, '', ''),
('lists', 'WNL_ABN', 'WNL_ABN', 67, 1, 0, '', ''),
('WNL_ABN', 'abn', 'ABNORMAL', 10, 0, 0, '', ''),
('WNL_ABN', 'abs', 'ABSENT', 40, 0, 0, '', ''),
('WNL_ABN', 'atropic', 'ATROPIC', 50, 0, 0, '', ''),
('WNL_ABN', 'dim', 'DIMINISHED', 20, 0, 0, '', ''),
('WNL_ABN', 'sparse', 'SPARSE', 30, 0, 0, '', ''),
('WNL_ABN', 'wnl', 'WNL', 0, 1, 0, '', ''),
('WNL_ABN', 'xerosis', 'XEROSIS', 60, 0, 0, '', ''),
('lists', 'xray_views', 'xray views', 68, 1, 0, '', ''),
('xray_views', '1', '2 Views', 0, 0, 0, '', ''),
('xray_views', '2', '3 Views', 1, 0, 0, '', '')
;
